name: Sync Fork

on:
  schedule:
    - cron: '0  8 * * *'
    - cron: '0 14 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        name: Sync Fork
        with:
          owner: SoStufo
          repo: tvheadend
          head: master
          base: master
          merge_method: merge
          pr_title: "Fork Sync: Merge 'tvheadend/master'"
          auto_merge: true
